[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm-v7a"
excluded-patches = "'Theme' 'Enable debugging'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm-v7a"
excluded-patches = "'Return YouTube Dislike' 'Theme' 'Enable debugging' 'Spoof device dimensions'"

